"""empty message

Revision ID: 205fd9719745
Revises: e40cc5c2a332
Create Date: 2018-09-07 16:18:41.511939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205fd9719745'
down_revision = 'e40cc5c2a332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'metric')
    op.add_column('meal_ingredients', sa.Column('metric', sa.String(length=16), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal_ingredients', 'metric')
    op.add_column('ingredients', sa.Column('metric', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
