"""empty message

Revision ID: 6f32b9ac7171
Revises: c9b77b950b79
Create Date: 2018-09-06 19:44:19.527080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f32b9ac7171'
down_revision = 'c9b77b950b79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_ingredients', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'meal_ingredients', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meal_ingredients', type_='foreignkey')
    op.drop_column('meal_ingredients', 'user_id')
    # ### end Alembic commands ###
