"""empty message

Revision ID: e40cc5c2a332
Revises: 6f32b9ac7171
Create Date: 2018-09-06 19:47:09.155986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e40cc5c2a332'
down_revision = '6f32b9ac7171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ingredients', 'users', ['user_id'], ['id'])
    op.drop_constraint('meal_ingredients_user_id_fkey', 'meal_ingredients', type_='foreignkey')
    op.drop_column('meal_ingredients', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_ingredients', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('meal_ingredients_user_id_fkey', 'meal_ingredients', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'ingredients', type_='foreignkey')
    op.drop_column('ingredients', 'user_id')
    # ### end Alembic commands ###
